Feature: Implement defender metrics
BlackbirdHQ/rustot pull request #70
Opened 2024-12-23 12:40 UTC by KennethKnudsen97

2024-12-30 10:44 UTC, KennethKnudsen97 commented
The structure for device custom metric takes up to much space as there is a lot of strings and vectors. 
![image](https://github.com/user-attachments/assets/90d8723f-621c-48bc-bd16-f1b6136796a2)


And the embassy pool size is 30K: 
![image](https://github.com/user-attachments/assets/7ad82e85-5144-464b-8390-f8e8fb979b5b)



The structure I made was the simplest structure in order to serialize the struct into the json object AWS expects: 
```rust 

pub struct Metric {
    #[serde(rename = "hed")]
    pub header: Header,

    #[serde(rename = "cmet")]
    pub custom_metrics: Option<
        LinearMap<String<MAX_CUSTOM_METRICS_NAME>, Vec<CustomMetric, 1>, MAX_CUSTOM_METRICS>,
    >,
}

pub enum CustomMetric {
    Number(i64),
    NumberList(Vec<u64, MAX_METRICS>),
    StringList(Vec<String<LOCAL_INTERFACE_SIZE>, MAX_METRICS>),
    IpList(Vec<String<REMOTE_ADDR_SIZE>, MAX_METRICS>),
}
```

This is the structure from AWS documentation: 
```json
{
  "header": {
    "report_id": 1530304554,
    "version": "1.0"
  },
  "metrics": {
    "listening_tcp_ports": {
      "ports": [
        {
          "interface": "eth0",
          "port": 24800
        },
        {
          "interface": "eth0",
          "port": 22
        },
        {
          "interface": "eth0",
          "port": 53
        }
      ],
      "total": 3
    },
    "listening_udp_ports": {
      "ports": [
        {
          "interface": "eth0",
          "port": 5353
        },
        {
          "interface": "eth0",
          "port": 67
        }
      ],
      "total": 2
    },
    "network_stats": {
      "bytes_in": 29358693495,
      "bytes_out": 26485035,
      "packets_in": 10013573555,
      "packets_out": 11382615
    },
    "tcp_connections": {
      "established_connections": {
        "connections": [
          {
            "local_interface": "eth0",
            "local_port": 80,
            "remote_addr": "192.168.0.1:8000"
          },
          {
            "local_interface": "eth0",
            "local_port": 80,
            "remote_addr": "192.168.0.1:8000"
          }
        ],
        "total": 2
      }
    }
  },
  "custom_metrics": {
    "MyMetricOfType_Number": [
      {
        "number": 1
      }
    ],
    "MyMetricOfType_NumberList": [
      {
        "number_list": [
          1,
          2,
          3
        ]
      }
    ],
    "MyMetricOfType_StringList": [
      {
        "string_list": [
          "value_1",
          "value_2"
        ]
      }
    ],
    "MyMetricOfType_IpList": [
      {
        "ip_list": [
          "172.0.0.0",
          "172.0.0.10"
        ]
      }
    ]
  }
}
```

I will change the structure of Metric to take a generic custom metric so that the user of the library can decide how custom metric should look like. Then its up to the user to satisfy the json structure required for custom metrics.

2025-01-02 10:16 UTC, KennethKnudsen97 commented
The new structure is this: 
```rust 
#[derive(Debug, Serialize)]
pub struct Metric<C: Serialize> {
    #[serde(rename = "hed")]
    pub header: Header,

    #[serde(rename = "cmet")]
    pub custom_metrics: C,
}
```

Now the user have to make sure that the custom metric they make will be serialized to follow aws json structure.
 
The user could do this by wrapping the metric in linearmap and vector: 
`LinearMap<String<24>, heapless::Vec<WifiMetric, 1>, 16>`. Or the user could also manually impl serde serialize in order to follow the structure and keep the CustomMetric very simple: 

```rust
 #[derive(Debug)]
        struct WifiMetric {
            signal_strength: u8,
        }

        impl Serialize for WifiMetric {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                // Create a serializer for the outer structure
                let mut outer = serializer.serialize_struct("WifiMetricWrapper", 1)?;

                // Wrap the `number` field in an array-like structure
                let inner_metric = {
                    struct InnerMetric {
                        number: u8,
                    }
                    impl Serialize for InnerMetric {
                        fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
                        where
                            S: serde::Serializer,
                        {
                            let mut inner = serializer.serialize_struct("InnerMetric", 1)?;
                            inner.serialize_field("number", &self.number)?;
                            inner.end()
                        }
                    }

                    InnerMetric {
                        number: self.signal_strength,
                    }
                };

                outer.serialize_field("MyMetricOfType_Number", &[inner_metric])?;
                outer.end()
            }
        }

```
Here we have WifiMetric with a field called signal_strength, if we just derived serialization and use             
`#[serde(rename="number")] ` the json structure would look like this: 

```json
{
    "hed": {
        "rid": 123123123123,
        "v": "1.0"
    },
    "cmet": {
        "number": 23
    }
}
```
This is missing the name of the metric and should be wrapped in an array like this: 
```json
{
    "hed": {
        "rid": 123123123123,
        "v": "1.0"
    },
    "cmet": {
        "MyMetricOfType_Number": [
            {
                "number": 23
            }
        ]
    }
}
```
But by using the custom serialize implementation we can wrap the simple Wifimetric with the name and an array to follow the structure. 

Implementing serde serialize is not the easiest so maybe we can do some magic with rust macros just like ShadowState.

2025-01-03 09:10 UTC, MathiasKoch reviewed
Awesome starting point! 
Really nice to see how fast a feature like this can be implemented! 

Dropped a few comments and observations, let's go over them together if there is anything you disagree with or something I missed.

Also, I think the general `Metric` struct can be improved a bit, but I think you might be right that it requires a custom derive macro.

2025-01-03 09:10 UTC, MathiasKoch commented on src/defender_metrics/aws_types.rs
> +
It feels like all of these could and should be made as referenced data instead? That way you don't need all the constant sizing, and as we are only every serializing, and never deserializing, it will still give an idiomatic feel to construct and use.

E.g.

```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct ListeningUdpPorts<'a> {
    #[serde(rename = "pts")]
    pub ports: Option<&'a [UdpPort<'a>]>,

    #[serde(rename = "t")]
    pub total: Option<u64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UdpPort<'a> {
    #[serde(rename = "pt")]
    pub port: u16,

    #[serde(rename = "if")]
    pub interface: Option<&'a str>,
}
```

2025-01-03 09:10 UTC, MathiasKoch commented on src/defender_metrics/data_types.rs
> +            version: String::<HEADER_VERSION_SIZE>::from_str("1.0").unwrap(), //FIXME: Don't
This can be made more idiomatic, without the constant size and without the unwrap by adding a `Version` struct (if it can only be major, minor). Even better if the version field can hold a full semver version, then use the semver crate.

```rust
struct Version {
    major: u8,
    minor: u8
}

impl Serialize for Version {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.collect_str(self)
    }
}

impl Display for Version {
    fn fmt(&self, formatter: &mut core::fmt::Formatter) -> core::fmt::Result {
        write!(formatter, "{}.{}.{}", self.major, self.minor, self.patch)
    }
}

```

```rust
#[derive(Debug, Serialize)]
pub struct Header {
    /// Monotonically increasing value. Epoch timestamp recommended.
    #[serde(rename = "rid")]
    pub report_id: i64,

    /// Version in Major.Minor format.
    #[serde(rename = "v")]
    pub version: Version,
}
```

2025-01-03 09:10 UTC, MathiasKoch commented on src/defender_metrics/data_types.rs
> +}
Again, consider using lifetimes and references, to rid the constant max and thus the large RAM overhead during construction of these.

2025-01-03 09:10 UTC, MathiasKoch commented on src/defender_metrics/mod.rs
> +        let mut subsctiption = self
typo

2025-02-07 07:43 UTC, MathiasKoch requested changes

2025-02-07 07:43 UTC, MathiasKoch commented on src/defender_metrics/data_types.rs
> +    // #[serde(rename = "rid")]
Are these `rename` supposed to be here? If not, could you remove them?

2025-02-07 07:43 UTC, MathiasKoch commented on src/defender_metrics/data_types.rs
> +        serializer.serialize_field("version", "1.0")?;
This does not seem quite finished?

2025-02-07 07:43 UTC, MathiasKoch commented on src/defender_metrics/data_types.rs
> +/// Format is `Version(Majo, Minor)`
```suggestion
/// Format is `Version(Major, Minor)`
```

2025-02-07 07:43 UTC, MathiasKoch commented on src/defender_metrics/data_types.rs
> +}
Could you possibly just add a very simple unit test on serializing these using serde?
Preferably both json & cbor

2025-02-07 07:43 UTC, MathiasKoch commented on src/defender_metrics/mod.rs
> +                            error!("An error happened when serializing metric with cbor");
This seems like something that should return a serialize error instead of just a log?

2025-02-07 07:43 UTC, MathiasKoch commented on src/defender_metrics/mod.rs
> +        self.mqtt.wait_connected().await;
Could you move this above the DeferredPayload? That way you don't need to hold onto the closure across an await point that could potentially be a while, depending on network situation. Compiler might not be able to optimize.

2025-02-07 07:43 UTC, MathiasKoch commented on tests/metric.rs
> +//! 3. Assert result from AWS
This part does not seem to happen? Not sure what would be the easiest way here, without pulling in a full AWS SDK.

I think what you do is okay for this, but maybe just change this comment to reflect what is actually happening?

2025-02-07 07:44 UTC, MathiasKoch commented
I assume both clippy, unit tests & integration tests run & pass locally?

2025-02-07 08:29 UTC, KennethKnudsen97 commented on src/defender_metrics/data_types.rs
> +    // #[serde(rename = "rid")]
I still haven't found a way to serialize Version to CBOR. 
I left the "serde rename" for convenience when I get it to work. 
I still don't really know what we should use version for right now.

2025-02-07 14:57 UTC, merged